version: '3'
services:
  eureka-server:
    image: partytime/eureka-server
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - MASTER_IP=$MASTER_IP
    ports:
     - 9999:9999
    hostname: eureka-server
    networks:
     - ingress
    deploy:
      replicas: 1
      placement:
      #指定部署的服务器标签
        constraints: [node.role == manager]

  config-server:
    image: partytime/config-server
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - MASTER_IP=$MASTER_IP
    ports:
     - 9998:9998
    hostname: config-server
    depends_on:
      - eureka-server
    networks:
      - ingress
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 50M



  api-gateway:
    image: partytime/api-gateway
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - MASTER_IP=$MASTER_IP
    extra_hosts:
      config-server: $MASTER_IP
    ports:
     - 8999:8999
    networks:
     - ingress
    depends_on:
     - eureka-server
     - config-server
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  user-service:
    image: partytime/user-service
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - MASTER_IP=$MASTER_IP
    extra_hosts:
      config-server: $MASTER_IP
    ports:
     - 8899:8899
    networks:
     - ingress
    deploy:
      replicas: 2
    depends_on:
       - eureka-server
       - config-server

networks:
  ingress:
    #代表外部已经存在的网络
    external: true