version: '3'
services:
  eureka-server:
    image: lwdocker.com:5000/eureka-server:1.0
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - MASTER_IP=$MASTER_IP
    ports:
     - 9999:9999
    hostname: eureka-server
    networks:
     - docker-lw
    deploy:
      replicas: 1
      placement:
      #指定部署的服务器标签 [node.role == manager]等等
        constraints: [node.id == 05474cmmg6i4lf7laa9e7r1q5]

  config-server:
    image: lwdocker.com:5000/config-server:1.0
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    ports:
     - 9998:9998
    hostname: config-server
    depends_on:
      - eureka-server
    networks:
      - docker-lw
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == 05474cmmg6i4lf7laa9e7r1q5]

  api-gateway:
    image: lwdocker.com:5000/api-gateway:1.0
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    extra_hosts:
      config-server: $MASTER_IP
    ports:
     - 8999:8999
    networks:
     - docker-lw
    depends_on:
     - eureka-server
     - config-server
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == 05474cmmg6i4lf7laa9e7r1q5]

  user-service:
    image: lwdocker.com:5000/user-service:1.0
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    ports:
     - 8899:8899
    networks:
     - docker-lw
    deploy:
      replicas: 3
    depends_on:
       - eureka-server
       - config-server

networks:
  docker-lw:
    #代表外部已经存在的网络
    external: true