eureka-server:
  image: partytime/eureka-server
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 9999:9999

config-server:
  image: partytime/config-server
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 9998:9998
  hostname: config-server


api-gateway:
  image: partytime/api-gateway
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  extra_hosts:
    config-server: $DOCKER_IP
    user-service: $DOCKER_IP
  ports:
   - 8999:8999

user-service:
  image: partytime/user-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  extra_hosts:
    config-server: $DOCKER_IP
  ports:
   - 8899:8899
