version: '3'
services:
  api-gateway:
    image: lwdocker.com:5000/api-gateway:1.0
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    ports:
     - 8999:8999
    networks:
     - docker-lw
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == 05474cmmg6i4lf7laa9e7r1q5]

  user-service:
    image: lwdocker.com:5000/user-service:1.0
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    ports:
     - 8899:8899
    networks:
     - docker-lw
    deploy:
      replicas: 2

networks:
  docker-lw:
    #代表外部已经存在的网络
    external: true